# Generated by Django 4.2 on 2023-04-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockets_bdf',
            name='data_added',
        ),
        migrations.RemoveField(
            model_name='rockets_bdf',
            name='t',
        ),
    ]
